[workspace]
members = [
  "zomes/file_storage",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "develop", package = "hc_utils"}
hdk3 = {git = "https://github.com/holochain/holochain", rev = "68a49be953ecf4ffa228633a197b7ba73350b803", package = "hdk3"}
holo_hash = {git = "https://github.com/holochain/holochain", rev = "68a49be953ecf4ffa228633a197b7ba73350b803", package = "holo_hash"}
