[workspace]
members = [
  "dnas/consumer/zomes/file_storage_gateway",
  "dnas/provider/zomes/file_storage",
  "crates/file_storage_types",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
